[package]
name = "yamlbug"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_yml = "0.0.12"
tokio = { version = "1.40.0", features = ["fs", "sync", "rt", "macros"] }
